#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”


sudo apt-get update
sudo apt-get install -y 
sudo chown -R ubuntu 
echo "Hello World!" > 
sudo sed -i "30i $ADD301_REDIRECT" 
sudo service lotfi restart
